"""End-to-end continual-learning loop on a synthetic switching task (spec 22 Stage A, 30).

Dynamic proof of the core claim: sequentially learn two conflicting contexts with
a real optimizer (Adam) on the LoRA scratchpad, commit each to its canonical
address, and show the agent simultaneously (a) learns the current context and
(b) retains the previous context EXACTLY under sparse top-1 gather — no game id.

The synthetic task uses identical observation distribution for both contexts but
mutually incompatible target policies (the section 17.1 conflict, rendered as a
behavioral cloning objective the scratch can fit).
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
import numpy as np
import optax

from tfns.castm import address as addr
from tfns.castm import agent as ag
from tfns.castm import synaptic as syn
from tfns.castm import transaction as tx


def _cfg():
    return ag.AgentConfig(
        obs_hw=16, frame_stack=4,
        conv_channels=(8, 16, 16), conv_kernels=(4, 3, 2), conv_strides=(2, 1, 1),
        dense_dim=32, gru_hidden=32, act_dim=18, action_embed_dim=8,
        d_q=16, d_k=16, ctx_hidden=24,
        comp_rank_conv=8, comp_rank_dense=8, comp_rank_head=8, n_slots=8,
    )


def _train_scratch_to_target(cfg, params, banks, k, obs, prev_a, prev_r, reset, main_h,
                             target_logits, steps=250, lr=3e-3, seed=0):
    """Optimize a fresh LoRA scratch bank (Adam) to match target logits at address k."""

    scratch = ag.init_scratch_banks(jax.random.PRNGKey(seed), cfg)
    opt = optax.adam(lr)
    opt_state = opt.init(scratch)

    def loss_fn(s):
        logits, _value, _h = ag.policy_step(params, banks, s, cfg, main_h, obs, prev_a, prev_r, reset, k)
        return jnp.mean((logits - target_logits) ** 2)

    loss_grad = jax.jit(jax.value_and_grad(loss_fn))
    last = None
    for _ in range(steps):
        last, grads = loss_grad(scratch)
        updates, opt_state = opt.update(grads, opt_state, scratch)
        scratch = optax.apply_updates(scratch, updates)
    return scratch, float(last)


def test_continual_two_context_learn_and_retain():
    cfg = _cfg()
    key = jax.random.PRNGKey(0)
    banks = ag.init_banks(key, cfg)
    params = ag.init_params(key, cfg)
    book = addr.empty_address_book(d_k=cfg.d_k, n_max=8, seed=1)
    book, c0 = addr.allocate_canonical(book)
    book, c1 = addr.allocate_canonical(book)
    k0, k1 = addr.code(book, c0), addr.code(book, c1)

    rng = np.random.default_rng(2)
    B = 16
    obs = jnp.asarray(rng.integers(0, 255, size=(B, cfg.obs_hw, cfg.obs_hw, cfg.frame_stack), dtype=np.uint8))
    prev_a = jnp.zeros((B,), jnp.int32)
    prev_r = jnp.zeros((B,), jnp.float32)
    reset = jnp.zeros((B,), bool)
    main_h = jnp.asarray(rng.standard_normal((B, cfg.gru_hidden)).astype(np.float32))

    # Two conflicting target policies on the SAME observations, generated by random
    # teacher scratch banks (so they are representable by a scratch of equal rank).
    def teacher_logits(seed):
        ts = ag.init_scratch_banks(jax.random.PRNGKey(seed), cfg)
        ts = {n: s.replace(B_s=s.B_s + 0.5 * jax.random.normal(jax.random.PRNGKey(seed + 1), s.B_s.shape))
              for n, s in ts.items()}
        logits, _v, _h = ag.policy_step(params, banks, ts, cfg, main_h, obs, prev_a, prev_r, reset, k0)
        return logits

    target0 = teacher_logits(100)
    target1 = teacher_logits(200)
    # The two targets really are different (conflicting contexts).
    assert float(jnp.mean((target0 - target1) ** 2)) > 1e-3

    base_loss0 = float(jnp.mean((ag.policy_step(params, banks, None, cfg, main_h, obs, prev_a, prev_r, reset, k0)[0] - target0) ** 2))

    # --- Learn context 0, commit to address 0 ---
    scratch0, final0 = _train_scratch_to_target(cfg, params, banks, k0, obs, prev_a, prev_r, reset, main_h, target0, seed=10)
    assert final0 < 0.5 * base_loss0, (final0, base_loss0)  # plasticity: loss dropped
    banks, rep0 = tx.commit_scratch_bank(banks, scratch0, book, c0)
    assert rep0["accepted"], rep0

    # Memory-only (no scratch) at address 0 reproduces the learned policy.
    logits0_mem = ag.policy_step(params, banks, None, cfg, main_h, obs, prev_a, prev_r, reset, k0, ctx_id=c0, sparse=True)[0]
    loss0_after_commit = float(jnp.mean((logits0_mem - target0) ** 2))
    assert loss0_after_commit < 0.5 * base_loss0

    snapshot_ctx0 = np.asarray(logits0_mem)

    # --- Learn context 1, commit to address 1 ---
    base_loss1 = float(jnp.mean((ag.policy_step(params, banks, None, cfg, main_h, obs, prev_a, prev_r, reset, k1)[0] - target1) ** 2))
    scratch1, final1 = _train_scratch_to_target(cfg, params, banks, k1, obs, prev_a, prev_r, reset, main_h, target1, seed=20)
    assert final1 < 0.5 * base_loss1, (final1, base_loss1)  # plasticity on new context
    banks, rep1 = tx.commit_scratch_bank(banks, scratch1, book, c1)
    assert rep1["accepted"], rep1

    # --- Retention: context 0 is EXACTLY unchanged after learning context 1 ---
    logits0_final = ag.policy_step(params, banks, None, cfg, main_h, obs, prev_a, prev_r, reset, k0, ctx_id=c0, sparse=True)[0]
    np.testing.assert_array_equal(np.asarray(logits0_final), snapshot_ctx0)

    # --- New context learned and retained at its own address ---
    logits1_final = ag.policy_step(params, banks, None, cfg, main_h, obs, prev_a, prev_r, reset, k1, ctx_id=c1, sparse=True)[0]
    loss1_final = float(jnp.mean((logits1_final - target1) ** 2))
    assert loss1_final < 0.5 * base_loss1
